AWSTemplateFormatVersion: 2010-09-09
Description: Create an S3 bucket
Resources:
  UdaBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: uda-iye-bucket
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
Outputs:
  WebsiteURL:
    Value: !GetAtt UdaBucket.WebsiteURL
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !GetAtt UdaBucket.DomainName
    Description: Name of S3 bucket to hold website content
  